### ISSUE TITLE
IFusionCachePlugin Usage

### ISSUE THREAD

**Issue by JoeShook** [JoeShook/ZiggyCreatures.FusionCache.Metrics#1]
https://github.com/JoeShook/FusionCacheMetricsPlayground/blob/7a9c2362765afa00645d61cffe65c72fbec750f9/examples/EventCountersPluginExampleDotNetCore/Startup.cs#L41

@jodydonetti check this area out.  I am injecting a `IFusionCachePlugin` two ways.  I have two caches in all these examples.  The first cache named "domain" is injected via the AddFusionCache.  The second cache is called "email" and I have to hand wire because I can't inject IFusionCachePlugin twice.  Seems OK.   Tell me what you think.  It is working fine.   Both cache's metrics are reporting correctly.  

There are plenty of opinions about one cache vs multiple caches but in this use case I very much want to record metrics about "domain" separate from "email".  And trying to make FusionCacheEventSource work with a collection of named counters turns into a nightmare and increases the CPU cycles and locks to resolve the correct counter.  Anyway IFusionCachePlugin does work.

Thinking more about this... I am not familiar with how to register multiple IFusionCachePlugins as singletons.

**Comment by JoeShook** [comment]
@jodydonetti also note in the project I am referencing the feature_plugin branch of FusionCache  on my desktop.

**Comment by jodydonetti** [comment]
> @jodydonetti also note in the project I am referencing the feature_plugin branch of FusionCache on my desktop.

Well now that I've release v0.1.5 (with official plugins support) you can reference directly the official nuget package!

**Comment by jodydonetti** [comment]
> I have two caches in all these examples. The first cache named "domain" is injected via the AddFusionCache. The second cache is called "email" and I have to hand wire because I can't inject IFusionCachePlugin twice. Seems OK. Tell me what you think. It is working fine.

Without DI there's no problem at all: multiple caches, multiple plugins, multiple everything, no problem.
With native .NET DI? Yep, you are right about it being kinda weird to have multiple singletons components, but that is just the way it is right now and we can't do anything about it, at least not without taking another path.

Basically it all boils down to this: in the native .NET DI container the way to go is via ctor injection, and with ctor injection you can only specify a param with a type, and that type will be used to resolve an instance. That's it.
Because of this there's no native way to have more than one of them (except via different scopes, or by making the service transient, but that is not what we are talking about here).

Something I'm thinking about (but haven't had the time yet to clear my mind) is maybe an additional approach similar to the multiple named HttpClient way (see [here](https://visualstudiomagazine.com/Blogs/Tool-Tracker/2019/09/mutliple-httpclients.aspx)).
It would also be familiar to existing .NET users, so maybe there's a point in that.

> Both cache's metrics are reporting correctly.
> [...]
> Anyway IFusionCachePlugin does work.

Yeah! Good to know 🎉

> Thinking more about this... I am not familiar with how to register multiple IFusionCachePlugins as singletons.

If we are talking about a single cache with multiple plugins (think a metrics plugin + a notifications plugin or whatever) it's very simple: you just do a `services.AddSingleton<IFusionCachePlugin>([...])` twice, and all of them will be picked up by the DI container when resolving an `IFusionCache` instance.

Example:

```csharp
[...]
services.AddSingleton<IFusionCachePlugin, MyMetricsPlugin>();
services.AddSingleton<IFusionCachePlugin, MyNotificationsPlugin>();
services.AddSingleton<IFusionCachePlugin, MyWhateverSuperDuperPlugin>();
[...]
```

Then, when working with your FusionCache instance, you will have 3 plugins running automatically.

Let me know how it goes, hope this helps.
